(define(problem satprob)
(:domain SimpleSatellite)
(:objects
  mem0 mem1 mem2 mem3 mem4 mem5 mem6 mem7 mem8 mem9 - memory
 img1 img2 img3 img4 img5 img6 img7 img8 img9 img10 img11 img12 img13 img14 img15 img16 img17 img18 img19 img20 img21 img22 img23 img24 img25 - image
)
(:init
  (sat_free)
  (= (image_score img1) 0)
  (= (image_score img2) 0)
  (= (image_score img3) 0)
  (= (image_score img4) 0)
  (= (image_score img5) 0)
  (= (image_score img6) 0)
  (= (image_score img7) 0)
  (= (image_score img8) 0)
  (= (image_score img9) 0)
  (= (image_score img10) 0)
  (= (image_score img11) 0)
  (= (image_score img12) 0)
  (= (image_score img13) 0)
  (= (image_score img14) 0)
  (= (image_score img15) 0)
  (= (image_score img16) 0)
  (= (image_score img17) 0)
  (= (image_score img18) 0)
  (= (image_score img19) 0)
  (= (image_score img20) 0)
  (= (image_score img21) 0)
  (= (image_score img22) 0)
  (= (image_score img23) 0)
  (= (image_score img24) 0)
  (= (image_score img25) 0)
  (= (total_score) 0)

  (memory_free mem1)
  (memory_free mem2)
  (memory_free mem3)
  (memory_free mem4)
  (memory_free mem5)
  (memory_free mem6)
  (memory_free mem7)
  (memory_free mem8)
  (memory_free mem9)

   (memory_taken mem0 img6)

(image_analysed mem0 img6)

  (at 50 (image_available img1))
  (at 58 (not (image_available img1)))
  (at 89 (image_available img4))
  (at 97 (not (image_available img4)))
  (at 14 (image_available img6))
  (at 22 (not (image_available img6)))
  (at 18 (image_available img12))
  (at 26 (not (image_available img12)))
  (at 63 (image_available img15))
  (at 71 (not (image_available img15)))
  (at 66 (image_available img16))
  (at 74 (not (image_available img16)))
  (at 65 (image_available img18))
  (at 73 (not (image_available img18)))
  (at 0 (image_available img22))
  (at 6 (not (image_available img22)))
  (at 76 (image_available img25))
  (at 84 (not (image_available img25)))
  (at 1 (dump_available))
  (at 37.0 (not (dump_available)))

)
(:goal (and
  (> (image_score img4) 0)
  (<= (image_score img4) 19.0)

  (> (image_score img8) 0)
  (<= (image_score img8) 15.0)

  (> (image_score img14) 0)
  (<= (image_score img14) 12.0)

(>= (total_score) 10)
))
(:metric maximize (+
  (image_score img4)
    (+ (image_score img8)
      (image_score img14)
    )
  )
)
)
