(define(problem satprob)
(:domain SimpleSatellite)
(:objects
  mem0 mem1 mem2 mem3 mem4 mem5 mem6 mem7 mem8 mem9 - memory
 img1 img2 img3 img4 img5 img6 img7 img8 img9 img10 img11 img12 img13 img14 img15 img16 img17 img18 img19 img20 - image
)
(:init
  (sat_free)
  (= (image_score img1) 0)
  (= (image_score img2) 0)
  (= (image_score img3) 0)
  (= (image_score img4) 0)
  (= (image_score img5) 0)
  (= (image_score img6) 0)
  (= (image_score img7) 0)
  (= (image_score img8) 0)
  (= (image_score img9) 0)
  (= (image_score img10) 0)
  (= (image_score img11) 0)
  (= (image_score img12) 0)
  (= (image_score img13) 0)
  (= (image_score img14) 0)
  (= (image_score img15) 0)
  (= (image_score img16) 0)
  (= (image_score img17) 0)
  (= (image_score img18) 0)
  (= (image_score img19) 0)
  (= (image_score img20) 0)
  (= (total_score) 0)

  (memory_free mem2)
  (memory_free mem3)
  (memory_free mem4)
  (memory_free mem5)
  (memory_free mem6)
  (memory_free mem7)
  (memory_free mem8)
  (memory_free mem9)

   (memory_taken mem0 img1)
   (memory_taken mem1 img15)

(image_analysed mem0 img1)
(image_analysed mem1 img15)

  (at 5 (image_available img1))
  (at 13 (not (image_available img1)))
  (at 19 (image_available img3))
  (at 27 (not (image_available img3)))
  (at 18 (image_available img6))
  (at 26 (not (image_available img6)))
  (at 26 (image_available img7))
  (at 34 (not (image_available img7)))
  (at 29 (image_available img16))
  (at 37 (not (image_available img16)))
  (at 18 (image_available img17))
  (at 26 (not (image_available img17)))
  (at 1 (dump_available))
  (at 22.0 (not (dump_available)))

)
(:goal (and
  (> (image_score img1) 0)
  (<= (image_score img1) 12.0)

  (> (image_score img3) 0)
  (<= (image_score img3) 13.0)

  (> (image_score img10) 0)
  (<= (image_score img10) 3.0)

  (> (image_score img17) 0)
  (<= (image_score img17) 14.0)

  (> (image_score img20) 0)
  (<= (image_score img20) 6.0)

(>= (total_score) 10)
))
(:metric maximize (+
  (image_score img1)
    (+ (image_score img3)
      (+ (image_score img10)
        (+ (image_score img17)
          (image_score img20)
        )
      )
    )
  )
)
)
