(define(problem satprob)
(:domain SimpleSatellite)
(:objects
  mem0 mem1 mem2 mem3 mem4 mem5 mem6 mem7 mem8 mem9 - memory
 img1 img2 img3 img4 img5 img6 img7 img8 img9 img10 img11 img12 img13 img14 img15 img16 img17 img18 img19 img20 img21 img22 img23 img24 img25 - image
)
(:init
  (sat_free)
  (= (image_score img1) 0)
  (= (image_score img2) 0)
  (= (image_score img3) 0)
  (= (image_score img4) 0)
  (= (image_score img5) 0)
  (= (image_score img6) 0)
  (= (image_score img7) 0)
  (= (image_score img8) 0)
  (= (image_score img9) 0)
  (= (image_score img10) 0)
  (= (image_score img11) 0)
  (= (image_score img12) 0)
  (= (image_score img13) 0)
  (= (image_score img14) 0)
  (= (image_score img15) 0)
  (= (image_score img16) 0)
  (= (image_score img17) 0)
  (= (image_score img18) 0)
  (= (image_score img19) 0)
  (= (image_score img20) 0)
  (= (image_score img21) 0)
  (= (image_score img22) 0)
  (= (image_score img23) 0)
  (= (image_score img24) 0)
  (= (image_score img25) 0)
  (= (total_score) 0)

  (memory_free mem4)
  (memory_free mem5)
  (memory_free mem6)
  (memory_free mem7)
  (memory_free mem8)
  (memory_free mem9)

   (memory_taken mem0 img23)
   (memory_taken mem1 img6)
   (memory_taken mem2 img11)
   (memory_taken mem3 img4)

(image_analysed mem0 img23)
(image_analysed mem1 img6)
(image_analysed mem2 img11)
(image_analysed mem3 img4)

  (at 32 (image_available img6))
  (at 40 (not (image_available img6)))
  (at 1 (image_available img7))
  (at 9 (not (image_available img7)))
  (at 48 (image_available img12))
  (at 56 (not (image_available img12)))
  (at 12 (image_available img19))
  (at 20 (not (image_available img19)))
  (at 48 (image_available img22))
  (at 56 (not (image_available img22)))
  (at 1 (dump_available))
  (at 2.0 (not (dump_available)))

)
(:goal (and
  (> (image_score img6) 0)
  (<= (image_score img6) 1.0)

  (> (image_score img9) 0)
  (<= (image_score img9) 2.0)

  (> (image_score img10) 0)
  (<= (image_score img10) 3.0)

  (> (image_score img11) 0)
  (<= (image_score img11) 3.0)

  (> (image_score img14) 0)
  (<= (image_score img14) 2.0)

  (> (image_score img22) 0)
  (<= (image_score img22) 2.0)

  (> (image_score img24) 0)
  (<= (image_score img24) 1.0)

  (> (image_score img25) 0)
  (<= (image_score img25) 3.0)

(>= (total_score) 4)
))
(:metric maximize (+
  (image_score img6)
    (+ (image_score img9)
      (+ (image_score img10)
        (+ (image_score img11)
          (+ (image_score img14)
            (+ (image_score img22)
              (+ (image_score img24)
                (image_score img25)
              )
            )
          )
        )
      )
    )
  )
)
)
