(define(problem satprob)
(:domain SimpleSatellite)
(:objects
  mem0 mem1 mem2 mem3 mem4 mem5 mem6 mem7 mem8 mem9 - memory
 img1 img2 img3 img4 img5 - image
)
(:init
  (sat_free)
  (= (image_score img1) 0)
  (= (image_score img2) 0)
  (= (image_score img3) 0)
  (= (image_score img4) 0)
  (= (image_score img5) 0)
  (= (total_score) 0)

  (memory_free mem6)
  (memory_free mem7)
  (memory_free mem8)
  (memory_free mem9)

   (memory_taken mem0 img3)
   (memory_taken mem1 img5)
   (memory_taken mem2 img1)
   (memory_taken mem3 img4)
   (memory_taken mem4 img2)
   (memory_taken mem5 img3)

(image_analysed mem0 img3)
(image_analysed mem1 img5)
(image_analysed mem2 img1)
(image_analysed mem3 img4)
(image_analysed mem4 img2)
(image_analysed mem5 img3)

  (at 348 (image_available img1))
  (at 356 (not (image_available img1)))
  (at 223 (image_available img2))
  (at 231 (not (image_available img2)))
  (at 312 (image_available img3))
  (at 320 (not (image_available img3)))
  (at 181 (image_available img4))
  (at 189 (not (image_available img4)))
  (at 125 (image_available img5))
  (at 133 (not (image_available img5)))
  (at 708 (image_available img1))
  (at 716 (not (image_available img1)))
  (at 583 (image_available img2))
  (at 591 (not (image_available img2)))
  (at 672 (image_available img3))
  (at 680 (not (image_available img3)))
  (at 541 (image_available img4))
  (at 549 (not (image_available img4)))
  (at 485 (image_available img5))
  (at 493 (not (image_available img5)))
  (at 1068 (image_available img1))
  (at 1076 (not (image_available img1)))
  (at 943 (image_available img2))
  (at 951 (not (image_available img2)))
  (at 1032 (image_available img3))
  (at 1040 (not (image_available img3)))
  (at 901 (image_available img4))
  (at 909 (not (image_available img4)))
  (at 845 (image_available img5))
  (at 853 (not (image_available img5)))
  (at 1428 (image_available img1))
  (at 1436 (not (image_available img1)))
  (at 1303 (image_available img2))
  (at 1311 (not (image_available img2)))
  (at 1392 (image_available img3))
  (at 1400 (not (image_available img3)))
  (at 1261 (image_available img4))
  (at 1269 (not (image_available img4)))
  (at 1205 (image_available img5))
  (at 1213 (not (image_available img5)))
  (at 1 (dump_available))
  (at 36.0 (not (dump_available)))
  (at 178.0 (dump_available))
  (at 216.0 (not (dump_available)))
  (at 358.0 (dump_available))
  (at 396.0 (not (dump_available)))
  (at 538.0 (dump_available))
  (at 576.0 (not (dump_available)))
  (at 718.0 (dump_available))
  (at 756.0 (not (dump_available)))
  (at 898.0 (dump_available))
  (at 936.0 (not (dump_available)))
  (at 1078.0 (dump_available))
  (at 1116.0 (not (dump_available)))
  (at 1258.0 (dump_available))
  (at 1296.0 (not (dump_available)))
  (at 1438.0 (dump_available))
  (at 1476.0 (not (dump_available)))

)
(:goal (and
  (> (image_score img1) 0)
  (<= (image_score img1) 2)

  (> (image_score img2) 0)
  (<= (image_score img2) 11)

  (> (image_score img3) 0)
  (<= (image_score img3) 3)

  (> (image_score img5) 0)
  (<= (image_score img5) 9)

(>= (total_score) 5)
))
(:metric maximize (+
  (image_score img1)
    (+ (image_score img2)
      (+ (image_score img3)
        (image_score img5)
      )
    )
  )
)
)
