
# Works for both torch and tf.
framework: tf
lambda: 0.95
kl_coeff: 0.5
clip_rewards: True
clip_param: 0.1
vf_clip_param: 10.0
entropy_coeff: 0.01
train_batch_size: 5000
rollout_fragment_length: 20
sgd_minibatch_size: 500
num_sgd_iter: 10
num_workers: 4
num_envs_per_worker: 4
batch_mode: truncate_episodes
observation_filter: NoFilter
num_gpus: 0
model:
    dim: 42
    vf_share_layers: True

# Only for evaluation runs, render the env.
evaluation_duration: 20
evaluation_interval: 10000
evaluation_config:
    render_env: True
render_env: False

